name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC+7
    - cron: "0 17 * * *"

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          #COMMIT_BY_ME: "true"
          #COMMIT_MESSAGE: "true"
          SHOW_UPDATED_DATE: "true"
          #UPDATED_DATE_FORMAT: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_COMMIT: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LOC_CHART: "true"
          #IGNORED_REPOS: "waka-readme-stats, my-first-repo"
          #SYMBOL_VERSION: 1
